name: Check package-lock for compromised dependencies

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
      rules_url:
        required: false
        type: string

jobs:
  check-lock:
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run package-lock check
        uses: staafl/javascript-check-dependencies-action@master
        with:
          rules_url: ${{ inputs.rules_url || 'https://raw.githubusercontent.com/staafl/javascript-check-dependencies-action/refs/heads/master/bad-deps.json' }}
